-- ------------------------------------------------------------
-- Item Basic Changes that require a DAT edit to change
-- ------------------------------------------------------------
-- Item Flags
SET @FLAG_AUG_SENDABLE   =      1; -- 0x00001
SET @FLAG_GM_ONLY        =      2; -- 0x00002
SET @FLAG_MYSTERY_BOX    =      4; -- 0x00004
SET @FLAG_MOG_GARDEN     =      8; -- 0x00008
SET @FLAG_CAN_SEND_ACCT  =     16; -- 0x00010
SET @FLAG_INSCRIBABLE    =     32; -- 0x00020
SET @FLAG_NOAUCTION      =     64; -- 0x00040
SET @FLAG_SCROLL         =    128; -- 0x00080
SET @FLAG_LINKSHELL      =    256; -- 0x00100
SET @FLAG_CANUSE         =    512; -- 0x00200
SET @FLAG_CANTRADENPC    =   1024; -- 0x00400
SET @FLAG_CANEQUIP       =   2048; -- 0x00800
SET @FLAG_NOSALE         =   4096; -- 0x01000
SET @FLAG_NODELIVERY     =   8192; -- 0x02000
SET @FLAG_EX             =  16384; -- 0x04000
SET @FLAG_RARE           =  32768; -- 0x08000
SET @FLAG_NO_RECYCLE     =  65536; -- 0x10000
SET @FLAG_NO_RARE_CHECK  = 131072; -- 0x20000

-- Remove Mail 2 Account for all items
UPDATE `item_basic` SET `flags` = `flags` & ~@FLAG_CAN_SEND_ACCT WHERE `flags` & @FLAG_CAN_SEND_ACCT;

-- Add flags back to certain items
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOSALE | @FLAG_RARE WHERE `itemid` = 120; -- F. Aquarium: add NoSale, Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOSALE | @FLAG_RARE WHERE `itemid` = 121; -- S. Aquarium: add NoSale, Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 582; -- Meteorite: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY | @FLAG_RARE WHERE `itemid` = 613; -- Faded Crystal: add NoAuction, NoDelivery, Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_INSCRIBABLE WHERE `itemid` = 671; -- Silver Sheet: add Inscribable
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX | @FLAG_NOAUCTION | @FLAG_NODELIVERY | @FLAG_RARE WHERE `itemid` = 905; -- Wyvern Skull: add Ex, NoAuction, NoDelivery, Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 950; -- Tahrongi Cactus: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1449; -- T. Whiteshell: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1450; -- L. Jadeshell: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1451; -- R. Stripeshell: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1452; -- O. Bronzepiece: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1453; -- M. Silverpiece: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1454; -- R. Goldpiece: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1455; -- 1 Byne Bill: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1456; -- 100 Byne Bill: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1457; -- 10,000 Byne Bill: add NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX | @FLAG_NOAUCTION | @FLAG_NODELIVERY WHERE `itemid` = 1695; -- Habaneros: add Ex, NoAuction, NoDelivery
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1857; -- Cordial Invite: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1904;   -- Ivory Chip
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1905;   -- Scarlet Chip
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1906;   -- Emerald Chip
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1907;   -- Silver Chip
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1908;   -- Cerulean Chip
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1909;   -- Smalt Chip
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1910;   -- Smoky Chip
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1930; -- Ecarlate Cloth: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1931; -- Argyro Rivet: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1932; -- Ut. Gold Thread: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1933; -- Ancient Brass: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1934; -- Benedict Silk: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1935; -- Benedict Yarn: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1936; -- Diabolic Silk: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1937; -- Diabolic Yarn: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1938; -- Rby. Silk Thread: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1939; -- Cardinal Cloth: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1940; -- Supple Skin: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1941; -- Light Filament: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1942; -- Snowy Cermet: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1943; -- White Rivet: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1944; -- Dark Orichalcum: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1945; -- Black Rivet: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1946; -- Smalt Leather: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1947; -- Fetid Lanolin: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1948; -- Coiled Yarn: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1949; -- Brown Doeskin: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1950; -- Chameleon Yarn: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1951; -- Charcoal Cotton: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1952; -- Scarlet Odoshi: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1953; -- Kurogane: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1954; -- Plaited Cord: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1955; -- Ebony Lacquer: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1956; -- Cbl. Myth. Sheet: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1957; -- Blue Rivet: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1958; -- Glittering Yarn: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 1959; -- Astral Leather: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1986; -- Orchid Chip  : add Ex
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1987; -- Charcoal Chip: add Ex
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 1988; -- Magenta Chip : add Ex
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX WHERE `itemid` = 2127; -- Metal Chip   : add Ex
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_INSCRIBABLE WHERE `itemid` = 2207; -- Celerity Salad: add Inscribable
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 2220; -- Lamian Bone Key: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 2223; -- Halv. Brass Key: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 2226; -- M. Blackscale Key: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 2306; -- Martial Ball Invite: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_INSCRIBABLE WHERE `itemid` = 2346; -- Tornado Salad: add Inscribable
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 2366; -- Whistle Coupon: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 2487; -- M. Camp Entry: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_INSCRIBABLE WHERE `itemid` = 4266; -- Ilm-long Sub: add Inscribable
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_INSCRIBABLE WHERE `itemid` = 4267; -- Btr. Nebimonite: add Inscribable
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX | @FLAG_NOAUCTION | @FLAG_NODELIVERY | @FLAG_NOSALE WHERE `itemid` = 4367; -- Batagreens
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 4368; -- 2Leaf Mandra Bud: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_RARE WHERE `itemid` = 5364; -- Tr. Grounds Key: add Rare
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_INSCRIBABLE WHERE `itemid` = 5647; -- Lik Kabob: add Inscribable
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_INSCRIBABLE WHERE `itemid` = 5648; -- Grilled Lik: add Inscribable
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION WHERE `itemid` = 14652; -- Protean Ring: add NoAuction
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_NOAUCTION WHERE `itemid` = 14653; -- Variable Ring: add NoAuction
UPDATE `item_basic` SET `flags` = `flags` | @FLAG_EX | @FLAG_LINKSHELL | @FLAG_NOAUCTION WHERE `itemid` = 19202; -- Smart Grenade: add Ex, Linkshell, NoAuction

-- DAT Stack size updates
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 496; -- Qdv. Chestplate (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 497; -- Gigas Socks (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 498; -- Yagudo Necklace (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 499; -- Gigas Necklace (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 501; -- Quadav Helm (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 505; -- Sheepskin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 507; -- Goblin Mail (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 508; -- Goblin Helm (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 510; -- Goblin Armor (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 511; -- Goblin Mask (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 554; -- Gold Orcmask (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 557; -- Ahriman Lens (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 564; -- Fingernail Sack (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 565; -- Teeth Sack (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 566; -- Goblin Cup (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 568; -- Goblin Die (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 582; -- Meteorite (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 596; -- Quadav Backplate (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 605; -- Pickaxe (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 610; -- San d'Or. Flour (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 611; -- Rye Flour (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 613; -- Faded Crystal (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 631; -- Horo Flour (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 640; -- Copper Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 641; -- Tin Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 642; -- Zinc Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 643; -- Iron Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 644; -- Mythril Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 645; -- Darksteel Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 646; -- Adaman Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 647; -- Molybdenum Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 677; -- White Steel (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 678; -- Aluminum Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 685; -- Khroma Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 688; -- Arrowwood Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 689; -- Lauan Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 690; -- Elm Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 691; -- Maple Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 692; -- Beech Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 693; -- Walnut Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 694; -- Chestnut Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 695; -- Willow Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 696; -- Yew Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 697; -- Holly Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 698; -- Ash Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 699; -- Oak Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 700; -- Mahogany Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 701; -- Rosewood Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 702; -- Ebony Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 703; -- Petrified Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 722; -- Divine Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 727; -- Dogwood Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 729; -- Bloodwood Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 736; -- Silver Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 737; -- Gold Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 738; -- Platinum Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 739; -- Orichalcum Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 769; -- Red Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 770; -- Blue Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 771; -- Yellow Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 772; -- Green Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 773; -- Translucent Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 774; -- Purple Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 775; -- Black Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 776; -- White Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 836; -- Damascene Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 837; -- Malboro Fiber (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 838; -- Spider Web (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 839; -- Crawler Cocoon (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 849; -- Undead Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 854; -- Cockatrice Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 857; -- Dhalmel Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 858; -- Wolf Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 859; -- Ram Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 860; -- Behemoth Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 861; -- Tiger Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 863; -- Coeurl Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 874; -- Amaltheia Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 876; -- Manta Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 878; -- Karakul Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 881; -- Crab Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 883; -- Behemoth Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 885; -- Turtle Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 886; -- Demon Skull (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 889; -- Beetle Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 892; -- Wyrm Skull (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 893; -- Giant Femur (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 895; -- Ram Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 896; -- Scorpion Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 897; -- Scorpion Claw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 899; -- Ifrit Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 901; -- Venomous Claw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 903; -- Dragon Talon (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 905; -- Wyvern Skull (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 906; -- Starmite Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 908; -- Adamantoise Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 909; -- Guivre's Skull (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 920; -- Malboro Vine (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 935; -- Ahriman Wing (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 950; -- Tahrongi Cactus (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 952; -- Poison Flour (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 959; -- Dahlia (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 1020; -- Sickle (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 1021; -- Hatchet (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1102; -- Blazing Peppers (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1109; -- Artificial Lens (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1116; -- Manticore Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1118; -- Antican Pauldron (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1119; -- Tonberry Coat (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1121; -- Antican Robe (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1122; -- Wyvern Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1123; -- Manticore Fang (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1124; -- Wyvern Wing (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1132; -- Raxa (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1155; -- Iron Sand (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1156; -- Crawler Calculus (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1158; -- Wandering Bulb (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1162; -- Tonberry Lantern (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1163; -- Manticore Hair (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1193; -- H. Q. Crab Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1196; -- Qiqirn Cape (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1239; -- Goblin Doll (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1240; -- Koma (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1255; -- Fire Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1256; -- Ice Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1257; -- Wind Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1258; -- Earth Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1259; -- Lightning Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1260; -- Water Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1261; -- Light Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1262; -- Dark Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1263; -- Leshonki Bulb (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1264; -- Grt. Boyahda Moss (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1265; -- 4Lf. Korrin Bud (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1268; -- Doll Gizmo (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1269; -- Mana Barrel (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1270; -- Arachne Web (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1271; -- Pigeon's Blood (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1272; -- Arioch Fang (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1273; -- Namtar Bone (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1274; -- Southern Pearl (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1275; -- Amemet Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1276; -- Tarasque Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1277; -- Lindwurm Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1279; -- Taffeta Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1280; -- Sarcenet Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1281; -- Cheviot Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1282; -- Flauros Whisker (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1283; -- Ose Whisker (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1288; -- Wooden Hktk. Eye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1289; -- Burning Hktk. Eye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1290; -- Earthen Hktk. Eye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1291; -- Golden Hktk. Eye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1292; -- Damp Hktk. Eye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1293; -- Narasimha Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1295; -- Twincoon (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1296; -- Yowie Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1299; -- Fire Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1300; -- Ice Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1301; -- Wind Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1302; -- Earth Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1303; -- Lightning Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1304; -- Water Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1305; -- Light Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1306; -- Dark Bead (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1311; -- Oxblood (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1312; -- Angel Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1313; -- Siren's Hair (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1409; -- Siren's Macrame (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1445; -- Freya's Tear (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1446; -- Lacquer Tree Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1458; -- Mammoth Tusk (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1463; -- Chronos Tooth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1464; -- Lancewood Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1465; -- Granite (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1466; -- Relic Iron (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1469; -- Wootz Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1470; -- Sparkling Stone (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1471; -- Sticky Rice (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1472; -- Gardenia Seed (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1473; -- H.Q. Scp. Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1474; -- Infinity Core (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1475; -- Curry Powder (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1516; -- Griffon Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1517; -- Giant Frozen Head (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1518; -- Colossal Skull (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1519; -- Fresh Orc Liver (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1588; -- Tufa (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1591; -- H. Q. Coeurl Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1592; -- Cactuar Root (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1614; -- Corse Bracelet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1615; -- Buffalo Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1616; -- Antlion Jaw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1617; -- Flytrap Leaf (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1618; -- Uragnite Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1620; -- Taurus Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1621; -- Taurus Wing (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1622; -- Bugard Tusk (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1624; -- Bugbear Mask (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1625; -- Moblin Helm (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1628; -- Buffalo Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1631; -- Moblin Armor (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1632; -- Moblin Mail (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1638; -- Moblin Mask (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1639; -- Corse Robe (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1640; -- Bugard Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1649; -- Scarlet Stone (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1650; -- Kopparnickel Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1654; -- Igneous Rock (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1655; -- Leather Pouch (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1656; -- Brass Tank (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 1657; -- Bundling Twine (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1663; -- Arnica Root (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1680; -- H. Q. Bugard Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1687; -- Recoll. of Fear (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1688; -- Recoll. of Pain (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1689; -- Recoll. of Guilt (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1691; -- Giant Scale (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1703; -- Kunwu Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1712; -- Cashmere Wool (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1718; -- M-bugard Tusk (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1719; -- Harajnite Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1724; -- Soulflayer Robe (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1725; -- Snow Lily (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1738; -- Shakudo Ingot (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1739; -- Balloon Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1740; -- Iolite (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1741; -- H. Q. Eft Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1765; -- Habu Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1766; -- Tiger Eye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1770; -- Oversized Fang (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1771; -- Dragon Bone (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1774; -- Red Gravel (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1816; -- Wyrm Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1817; -- Cactus Arm (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1836; -- Marble (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1840; -- Semolina (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1841; -- Unicorn Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1843; -- Spectral Crimson (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1844; -- Spect. Goldenrod (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1860; -- Moblin Putty (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1861; -- Moblin Sheepskin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1863; -- M. Sheep Wool (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1864; -- H.Q. Antlion Jaw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1886; -- Sieglinde Putty (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1888; -- Silica (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1889; -- White Sand (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1890; -- River Foliage (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1891; -- Sea Foliage (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1892; -- Desalinator (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1893; -- Salinator (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1894; -- Goldfish Set (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1895; -- Freshwater Set (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1896; -- Saltwater Set (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1930; -- Ecarlate Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1931; -- Argyro Rivet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1932; -- Ut. Gold Thread (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1933; -- Ancient Brass (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1934; -- Benedict Silk (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1935; -- Benedict Yarn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1936; -- Diabolic Silk (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1937; -- Diabolic Yarn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1938; -- Rby. Silk Thread (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1939; -- Cardinal Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1940; -- Supple Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1941; -- Light Filament (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1942; -- Snowy Cermet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1943; -- White Rivet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1944; -- Dark Orichalcum (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1945; -- Black Rivet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1946; -- Smalt Leather (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1947; -- Fetid Lanolin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1948; -- Coiled Yarn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1949; -- Brown Doeskin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1950; -- Chameleon Yarn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1951; -- Charcoal Cotton (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1952; -- Scarlet Odoshi (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1953; -- Kurogane (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1954; -- Plaited Cord (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1955; -- Ebony Lacquer (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1956; -- Cbl. Myth. Sheet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1957; -- Blue Rivet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1958; -- Glittering Yarn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1959; -- Astral Leather (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1973; -- Vivio Femur (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1974; -- Vivio Crab Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1975; -- Vi. Scorpion Claw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1979; -- Leech Saliva (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1980; -- Antican Acid (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1984; -- Snapping Mole (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 1985; -- Helmet Mole (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2002; -- Beast Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2009; -- Coral Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2016; -- Loam (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2121; -- Ovinnik Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2123; -- Catoblepas Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2126; -- Orpiment (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 2128; -- Spindle (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 2129; -- Tanning Vat (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 2130; -- Shagreen File (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 2131; -- Triturator (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2139; -- Fr. Dhalmel Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2140; -- Fragrant Ram Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2142; -- Wailing Ram Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 2143; -- Mandrel (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 2144; -- Workshop Anvil (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 2145; -- Zephyr Thread (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2147; -- Marid Tusk (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2151; -- Marid Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2153; -- Qiqirn Sandbag (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2157; -- Imp Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2158; -- Hydra Fang (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2160; -- Troll Pauldron (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2161; -- Troll Vambrace (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2162; -- Mamool Ja Helmet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2165; -- Qutrub Gorget (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2166; -- Marid Hair (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2167; -- Lamian Armlet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2168; -- Cerberus Claw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2169; -- Cerberus Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2171; -- Colibri Beak (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2173; -- Wam. Cocoon (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2206; -- Chocolixir (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2207; -- Celerity Salad (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2220; -- Lamian Bone Key (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2223; -- Halv. Brass Key (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2226; -- M. Blackscale Key (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2227; -- Mamool Ja Collar (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2228; -- Luminium Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2237; -- Imperial Flour (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2334; -- Poroggo Hat (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2335; -- Soulfl. Tentacle (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2336; -- Soulflayer Staff (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2343; -- La Theine Millet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2345; -- Hi-Chocolixir (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2346; -- Tornado Salad (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2355; -- Ja Ja's Chestplt. (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2356; -- Gurfurlur's Helmet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2357; -- Medusa's Armlet (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2359; -- Star Sapphire (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2361; -- Ameretat Vine (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2367; -- Gysahl Slop (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2368; -- Deluxe Carrot (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2369; -- Deluxe Worm (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2371; -- Khimaira Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2372; -- Khimaira Mane (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2373; -- Khimaira Tail (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2379; -- Ylw. Chocobo Dye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2380; -- Red Chocobo Dye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2381; -- Blue Chocobo Dye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2382; -- Grn. Chocobo Dye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2383; -- Blk. Chocobo Dye (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2417; -- Aht Urhgan Brass (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2420; -- Luminous Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2421; -- Spirit Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2426; -- Wivre Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2427; -- Wivre Maul (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2428; -- Wivre Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2465; -- Rubber Cap (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2466; -- Rubber Harness (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2467; -- Rubber Gloves (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2468; -- Rubber Chausses (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2469; -- Rubber Soles (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2470; -- Nethereye Chain (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2471; -- Netherfield Chain (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2472; -- Netherspirit Chain (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2473; -- Nethercant Chain (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2474; -- Netherpact Chain (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2504; -- H. Qdv. Chestplate (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2505; -- H. Qdv. Backplate (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2507; -- Lycopodium Flower (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2510; -- Orc Helm (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2511; -- Orc Pauldron (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2512; -- Lynx Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2513; -- Rafflesia Vine (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2515; -- Sandworm Fang (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2516; -- Sandworm Shell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2518; -- Smilodon Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2519; -- Yagudo Osode (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2520; -- Yagudo Kote (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2521; -- Gnole Claw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2523; -- Peiste Skin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2524; -- Peiste Stinger (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2531; -- Obsidian (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2532; -- Teak Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2534; -- Jacaranda Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2542; -- Goblin Mess Tin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2543; -- Goblin Weel (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2544; -- Smilodon Collar (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2545; -- Lynx Collar (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2552; -- Campaign Voucher (retail 99 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2652; -- Gigas Helm (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2653; -- Gigas Gauntlets (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2654; -- Dark Ixion Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2655; -- Dark Ixion Tail (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2656; -- Luminian Thread (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2657; -- Flameshun Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2658; -- Silkworm Thread (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2659; -- Canvas Toile (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2660; -- Pantin Wire (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2661; -- Corduroy Cloth (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2714; -- Filet Lace (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2715; -- Gold Stud (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2716; -- Brilliantine (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2717; -- Electrum Stud (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2729; -- Hydrangea (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2745; -- Bonanza Kupon B (retail 99 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2746; -- Bonanza Kupon X (retail 99 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2750; -- Amphiptere Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2752; -- Amph. Whisker (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2753; -- Amphiptere Claw (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2754; -- Ruszor Fang (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2755; -- Ruszor Hide (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2761; -- Feyweald Log (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2763; -- Swamp Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2765; -- Fool's Gold Ore (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 2769; -- Buggane Horn (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4104; -- Fire Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4105; -- Ice Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4106; -- Wind Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4107; -- Earth Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4108; -- Lightning Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4109; -- Water Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4110; -- Light Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4111; -- Dark Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4318; -- Bibiki Urchin (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4368; -- 2Leaf Mandra Bud (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4486; -- Dragon Heart (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4508; -- Royal Jelly (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 4545; -- Gysahl Greens (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 4567; -- Moon Carrot (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5187; -- Elshimo Coconut (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5286; -- Burning Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5287; -- Bitter Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5288; -- Fleeting Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5289; -- Profane Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5290; -- Startling Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5291; -- Somber Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5292; -- Radiant Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5293; -- Malevolent Cluster (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5365; -- Incus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5366; -- Castellanus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5367; -- Cumulus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5368; -- Radiatus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5369; -- Stratus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5370; -- Cirrocumulus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5371; -- Undulatus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5372; -- Virga Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5373; -- Duplicatus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5374; -- Opacus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5375; -- Praecipitatio Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5376; -- Pannus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5377; -- Fractus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5378; -- Congestus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5379; -- Nimbus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5380; -- Velum Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5381; -- Pileus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5382; -- Mediocris Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5383; -- Humilus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5384; -- Spissatus Cell (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 5410; -- Vrt. Stone Pouch (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5680; -- Agaricus (retail 12 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5735; -- Ctn. Purse (Alx.) (retail 99 -> 1)
UPDATE `item_basic` SET `stackSize` = 1 WHERE `itemid` = 5736; -- Lin. Purse (Alx.) (retail 99 -> 1)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 16992; -- Slice of Bluetail (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 16993; -- Peeled Crayfish (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 16994; -- Slice of Carp (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 16996; -- Sardine Ball (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 16997; -- Crayfish Ball (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 16998; -- Insect Ball (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 16999; -- Trout Ball (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17000; -- Meatball (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17003; -- Super Scoop (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17005; -- Lufaise Fly (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17006; -- Drill Calamary (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17007; -- Dwarf Pugil (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17296; -- Pebble (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17304; -- Fuma Shuriken (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17392; -- Sliced Sardine (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17393; -- Sliced Cod (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17394; -- Peeled Lobster (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17395; -- Lugworm (retail 99 -> 12)
UPDATE `item_basic` SET `stackSize` = 12 WHERE `itemid` = 17396; -- Little Worm (retail 99 -> 12)
